### ISSUE TITLE
For unix based systems, the spark is a dependency

### ISSUE THREAD

**Issue by abitofalchemy** [chan150/TrillionG#1]
spark-2.1.0 (or higher)

On centOS, before running local,  this requirement can be satisfied as follows:
```
wget https://d3kbcqa49mib13.cloudfront.net/spark-2.2.0-bin-hadoop2.7.tgz
sudo tar zxvf spark-2.2.0-bin-hadoop2.7.tgz -C /opt
sudo ln -fs spark-2.2.0-bin-hadoop2.7 /opt/spark
```
Then set the environment variable `SPARK_HOME`, add the following to `.bashrc` or `.bash_profile`

```
# Insert these lines into your ~/.bash_profile:
export SPARK_HOME=/opt/spark
PATH=$PATH:$SPARK_HOME/bin
export PATH
# Then exit the text editor and return to the command line.
```
The above is from [this link](https://sparkour.urizone.net/recipes/installing-ec2/)

With this set, comment out the SPARK_HOME line in the run-local.sh

HTH

**Comment by abitofalchemy** [comment]
Also, when running

I think this code depends on hadoop being installed? Below is the first 
```
bash run.sh output -n 20 -m 120 -format tsv -noise 0.1
run.sh: line 5: hadoop: command not found
```

... and down below I get 

```
17/09/28 10:56:31 ERROR StandaloneSchedulerBackend: Application has been killed. Reason: All masters are unresponsive! Giving up.
```

**Comment by chan150** [comment]
When run on distributed machine, you have to set SPARK (and HADOOP for distributed file system).

If you want to run on single machine, you just try to use "run-local.sh" instead of "run.sh".
